title = "Alpaca Driver (Focuser)"

[network]
ip_address = ''             # Any address
port = 5555

[server]
location = 'Otter Creek Research'  # Anything you want here
verbose_driver_exceptions = true

[focuser0]
port = 'COM3'

[logging]
log_level = 'INFO'
log_to_stdout = false
max_size_mb = 5
num_keep_logs = 10
